import { Inter } from "next/font/google";
import Header from "./components/shared/header";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "./index.scss";
import { getSession, logout } from "@/lib/auth";
import { searchRentals } from "@/lib/controllers/rental";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const isLoggedIn = (await getSession()) || false;

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          isLoggedIn={isLoggedIn}
          onSearchAction={searchRentals}
          logout={logout}
        />
        <div className="container rwm-container">{children}</div>
      </body>
    </html>
  );
}
