import { Inter } from "next/font/google";
import Header from "./components/shared/header";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "bootstrap/dist/css/bootstrap.min.css";
import "./index.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="container rwm-container">{children}</div>
      </body>
    </html>
  );
}
